import { createHash, randomUUID } from 'node:crypto';
import { gunzipSync, gzipSync } from 'node:zlib';
import { query, withTransaction } from '../database/postgres.js';

// Usuários, hashes de senha, credenciais OAuth e cache Redis são excluídos intencionalmente.
export const BACKUP_TABLES=['categorias','profiles','livros','library_files','works','work_files','reading_state','background_jobs','source_sync_state','saved_views','book_preferences','series','work_series','offline_items','cache_entries','integrity_reports','reader_metrics','feature_flags','duplicate_decisions'];
const sha=(value)=>createHash('sha256').update(value).digest('hex');
function decode(buffer){let payload;try{payload=JSON.parse(gunzipSync(buffer).toString('utf8'));}catch{throw Object.assign(new Error('Arquivo de backup inválido ou corrompido.'),{statusCode:400});}if(payload?.format!=='araru-postgresql-backup'||payload.version!==3||!payload.data)throw Object.assign(new Error('Formato de backup não suportado.'),{statusCode:400});const expected=sha(JSON.stringify({schemaVersion:payload.schemaVersion,data:payload.data}));if(expected!==payload.integrity?.checksum)throw Object.assign(new Error('Checksum do backup inválido.'),{statusCode:400});return payload;}
async function tableColumns(client,table){const {rows}=await client.query("SELECT column_name,data_type,is_identity FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position",[table]);return rows;}
async function restoreInto(payload){await withTransaction(async(client)=>{await client.query("SET CONSTRAINTS ALL DEFERRED").catch(()=>{});for(const table of [...BACKUP_TABLES].reverse())await client.query(`DELETE FROM "${table}"`);for(const table of BACKUP_TABLES){const columns=await tableColumns(client,table);const allowed=new Map(columns.map((column)=>[column.column_name,column]));for(const source of Array.isArray(payload.data[table])?payload.data[table]:[]){const entries=Object.entries(source).filter(([key])=>allowed.has(key));if(!entries.length)continue;const names=entries.map(([key])=>`"${key}"`).join(',');const values=entries.map(([key,value])=>allowed.get(key).data_type==='jsonb'?JSON.stringify(value):value);const placeholders=entries.map(([key],index)=>`$${index+1}${allowed.get(key).data_type==='jsonb'?'::jsonb':''}`).join(',');if(table==='background_jobs'&&['queued','running'].includes(source.status)){const status=entries.findIndex(([key])=>key==='status');const error=entries.findIndex(([key])=>key==='error');if(status>=0)values[status]='failed';if(error>=0)values[error]='Interrompido pela restauração do backup.';}await client.query(`INSERT INTO "${table}" (${names}) VALUES (${placeholders})`,values);}}
  });}
export async function criarBackup(){const data={};for(const table of BACKUP_TABLES){const result=await query(`SELECT * FROM "${table}"`);data[table]=result.rows;}const version=await query('SELECT COALESCE(MAX(version),0)::int AS version FROM schema_migrations');const schemaVersion=version.rows[0].version;const core={schemaVersion,data};const createdAt=new Date().toISOString();const payload={format:'araru-postgresql-backup',version:3,schemaVersion,createdAt,metadata:{application:'Araru',database:'postgresql',tables:Object.fromEntries(BACKUP_TABLES.map((table)=>[table,data[table].length])),excluded:['users','secure_credentials','redis']},integrity:{algorithm:'sha256',checksum:sha(JSON.stringify(core))},data};const buffer=gzipSync(Buffer.from(JSON.stringify(payload)),{level:9});await query('INSERT INTO backup_history(id,filename,checksum,size,schema_version,verified) VALUES($1,$2,$3,$4,$5,TRUE)',[randomUUID(),`araru-${createdAt.slice(0,10)}.json.gz`,payload.integrity.checksum,buffer.length,schemaVersion]);await query('DELETE FROM backup_history WHERE id NOT IN (SELECT id FROM backup_history ORDER BY created_at DESC LIMIT 20)');return buffer;}
export async function verificarBackup(buffer){const payload=decode(buffer);return{valid:true,version:payload.version,schemaVersion:payload.schemaVersion,checksum:payload.integrity.checksum,tables:Object.fromEntries(BACKUP_TABLES.map((table)=>[table,(payload.data[table]||[]).length]))};}
export function previewRestore(buffer){const payload=decode(buffer);return{dryRun:true,version:payload.version,schemaVersion:payload.schemaVersion,createdAt:payload.createdAt,checksum:payload.integrity.checksum,tables:Object.fromEntries(BACKUP_TABLES.map((table)=>[table,(payload.data[table]||[]).length]))};}
export async function restaurarBackup(buffer){const payload=decode(buffer);await restoreInto(payload);return{restoredAt:new Date().toISOString(),verified:true,tables:Object.fromEntries(BACKUP_TABLES.map((table)=>[table,(payload.data[table]||[]).length]))};}
