import { randomUUID } from 'node:crypto';
import { access, stat } from 'node:fs/promises';
import { constants } from 'node:fs';
import { URL } from 'node:url';
import { query } from '../database/postgres.js';
import { encrypt, decrypt, mask } from './secretEncryptionService.js';

const providers = [{ id: 'local', name: 'Local', capabilities: ['read','scan'] }, { id: 'google_drive', name: 'Google Drive', capabilities: ['read','scan'] }, { id: 'cloudflare_r2', name: 'Cloudflare R2', capabilities: ['read','scan'] }];
function clean(input = {}) { const provider = String(input.provider || ''); if (!providers.some((item) => item.id === provider)) throw Object.assign(new Error('Provider inválido.'), { statusCode: 400 }); const config = { ...(input.config || {}) }; if (provider === 'local' && (!config.path || !String(config.path).startsWith('/'))) throw Object.assign(new Error('O path local deve ser absoluto.'), { statusCode: 400 }); if (provider === 'cloudflare_r2') { try { const endpoint = new URL(config.endpoint); if (endpoint.protocol !== 'https:') throw new Error(); } catch { throw Object.assign(new Error('Endpoint R2 inválido; use uma URL HTTPS.'), { statusCode: 400 }); } if (!config.bucket) throw Object.assign(new Error('Bucket R2 obrigatório.'), { statusCode: 400 }); } return { provider, config, credentials: input.credentials || {} }; }
function publicRow(row) { return { id: row.id, name: row.name, provider: row.provider, enabled: row.enabled, config: row.config, status: row.status, lastTestedAt: row.last_tested_at, lastErrorCode: row.last_error_code, lastErrorMessage: row.last_error_message, credentialsConfigured: Boolean(row.encrypted_credentials), accessKeyIdPreview: row.provider === 'cloudflare_r2' ? mask(row.config?.accessKeyIdPreview) : undefined, version: Number(row.version) }; }
export function listProviders() { return providers; }
export async function listConnections() { const { rows } = await query('SELECT * FROM storage_connections ORDER BY name'); return rows.map(publicRow); }
export async function getConnection(id) { const { rows } = await query('SELECT * FROM storage_connections WHERE id=$1', [id]); return rows[0] ? publicRow(rows[0]) : null; }
export async function saveConnection(input, userId) { const { provider, config, credentials } = clean(input); const id = input.id || randomUUID(); const current = input.id ? (await query('SELECT * FROM storage_connections WHERE id=$1', [id])).rows[0] : null; const encrypted = Object.keys(credentials).length ? encrypt(credentials, `${id}:${provider}`) : current?.encrypted_credentials || null; if (!encrypted && provider !== 'local') throw Object.assign(new Error('Credenciais são obrigatórias.'), { statusCode: 400 }); const safeConfig = { ...config }; delete safeConfig.accessKeyId; delete safeConfig.secretAccessKey; delete safeConfig.refreshToken; if (credentials.accessKeyId) safeConfig.accessKeyIdPreview = mask(credentials.accessKeyId); await query(`INSERT INTO storage_connections(id,name,provider,enabled,config,encrypted_credentials,encryption_version,encryption_key_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8,$9,$9) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,provider=EXCLUDED.provider,enabled=EXCLUDED.enabled,config=EXCLUDED.config,encrypted_credentials=EXCLUDED.encrypted_credentials,encryption_version=EXCLUDED.encryption_version,encryption_key_id=EXCLUDED.encryption_key_id,updated_by=EXCLUDED.updated_by,updated_at=NOW(),version=storage_connections.version+1`, [id, String(input.name || provider).trim(), provider, input.enabled !== false, JSON.stringify(safeConfig), encrypted ? JSON.stringify(encrypted) : null, encrypted?.version || null, encrypted?.keyId || null, userId]); return getConnection(id); }
export async function testConnection(id) { const { rows } = await query('SELECT * FROM storage_connections WHERE id=$1', [id]); const row = rows[0]; if (!row) return null; try { if (row.provider === 'local') { const info = await stat(row.config.path); await access(row.config.path, constants.R_OK); if (!info.isDirectory()) throw Object.assign(new Error('Path não é diretório.'), { code: 'NOT_DIRECTORY' }); } else { decrypt(row.encrypted_credentials, `${id}:${row.provider}`); } await query("UPDATE storage_connections SET status='connected',last_tested_at=NOW(),last_error_code=NULL,last_error_message=NULL,updated_at=NOW() WHERE id=$1", [id]); return getConnection(id); } catch (error) { await query('UPDATE storage_connections SET status=\'error\',last_tested_at=NOW(),last_error_code=$1,last_error_message=$2,updated_at=NOW() WHERE id=$3', [error.code || 'TEST_FAILED', String(error.message).slice(0, 240), id]); throw Object.assign(new Error('Não foi possível validar a conexão.'), { statusCode: 422, code: error.code || 'TEST_FAILED' }); } }
export async function deleteConnection(id) { const used = await query('SELECT COUNT(*)::int AS total FROM library_sources WHERE connection_id=$1', [id]); if (Number(used.rows[0].total)) throw Object.assign(new Error(`A conexão é usada por ${used.rows[0].total} source(s).`), { statusCode: 409, code: 'CONNECTION_IN_USE' }); const result = await query('DELETE FROM storage_connections WHERE id=$1', [id]); return Boolean(result.rowCount); }
export async function listSources(libraryId) { const { rows } = await query('SELECT id,library_id AS "libraryId",connection_id AS "connectionId",name,path_or_prefix AS "pathOrPrefix",enabled,scan_mode AS "scanMode" FROM library_sources WHERE library_id=$1 ORDER BY name', [libraryId]); return rows; }
export async function saveSource(libraryId, input) { if (!input?.connectionId || !input?.pathOrPrefix) throw Object.assign(new Error('Connection e path são obrigatórios.'), { statusCode: 400 }); const id = input.id || randomUUID(); await query(`INSERT INTO library_sources(id,library_id,connection_id,name,path_or_prefix,enabled,scan_mode) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET connection_id=EXCLUDED.connection_id,name=EXCLUDED.name,path_or_prefix=EXCLUDED.path_or_prefix,enabled=EXCLUDED.enabled,scan_mode=EXCLUDED.scan_mode,updated_at=NOW()`, [id, libraryId, input.connectionId, input.name || input.pathOrPrefix, input.pathOrPrefix, input.enabled !== false, input.scanMode || 'incremental']); return (await listSources(libraryId)).find((source) => source.id === id); }
export async function deleteSource(libraryId, id) { const result = await query('DELETE FROM library_sources WHERE library_id=$1 AND id=$2', [libraryId, id]); return Boolean(result.rowCount); }
