import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { env, oauth2Client } from '../config/drive.js';
import { query } from '../database/postgres.js';
import { logger } from './logger.js';

function encryptionKey(){const secret=env.appAccessSecret||env.googleClientSecret;if(!secret)throw new Error('APP_ACCESS_SECRET ou GOOGLE_CLIENT_SECRET é necessário para proteger o OAuth.');return createHash('sha256').update(secret).digest();}
function encrypt(value){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return[iv,cipher.getAuthTag(),encrypted].map((part)=>part.toString('base64url')).join('.');}
function decrypt(value){const [iv,tag,encrypted]=String(value||'').split('.').map((part)=>Buffer.from(part,'base64url'));if(!iv?.length||!tag?.length||!encrypted?.length)throw new Error('Credencial OAuth persistida inválida.');const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(encrypted),decipher.final()]).toString('utf8'));}
export async function carregarCredenciaisOAuth({apply=true}={}){const {rows}=await query("SELECT encrypted_payload FROM secure_credentials WHERE provider='google-drive'");if(!rows[0])return null;try{const tokens=decrypt(rows[0].encrypted_payload);if(apply)oauth2Client.setCredentials(tokens);return tokens;}catch(error){logger.warn('oauth.credentials.load_failed',{error});return null;}}
export async function salvarCredenciaisOAuth(tokens={}){const atuais=await carregarCredenciaisOAuth({apply:false})||{};const merged={...atuais,...tokens,refresh_token:tokens.refresh_token||atuais.refresh_token};await query("INSERT INTO secure_credentials(provider,encrypted_payload,updated_at) VALUES('google-drive',$1,NOW()) ON CONFLICT(provider) DO UPDATE SET encrypted_payload=EXCLUDED.encrypted_payload,updated_at=NOW()",[encrypt(merged)]);oauth2Client.setCredentials(merged);return merged;}
export async function removerCredenciaisOAuth(){await query("DELETE FROM secure_credentials WHERE provider='google-drive'");oauth2Client.setCredentials({});}
export async function obterEstadoSincronizacao(source='drive'){const {rows}=await query('SELECT source,cursor,mode,last_sync_at AS "lastSyncAt",last_error AS "lastError" FROM source_sync_state WHERE source=$1',[source]);return rows[0]||null;}
export async function salvarEstadoSincronizacao(source,{cursor=null,mode='full',error=null}={}){await query('INSERT INTO source_sync_state(source,cursor,mode,last_sync_at,last_error,updated_at) VALUES($1,$2,$3,NOW(),$4,NOW()) ON CONFLICT(source) DO UPDATE SET cursor=EXCLUDED.cursor,mode=EXCLUDED.mode,last_sync_at=NOW(),last_error=EXCLUDED.last_error,updated_at=NOW()',[source,cursor,mode,error?String(error.message||error).slice(0,2000):null]);}
