import { randomUUID } from 'node:crypto';
import { query } from '../database/postgres.js';
import { backgroundJobs } from './backgroundJobs.js';

const names = { cover: ['Generate covers', 'Generate or refresh a book cover.'], 'catalog-reconcile': ['Catalog reconciliation', 'Reconcile connected libraries and the catalog.'], 'comic-index': ['Comic indexing', 'Build the comic reading index.'], metadata: ['Metadata refresh', 'Refresh book metadata.'] };
const cronPart = (value, current, min, max) => value === '*' || value.split(',').some((part) => { const [start, end, step = '1'] = part.split('/').map(Number); if (part.includes('/')) return current >= (Number.isFinite(start) ? start : min) && current <= (Number.isFinite(end) ? end : max) && (current - (Number.isFinite(start) ? start : min)) % step === 0; return Number(part) === current; });
function cronMatches(cron, date) { const parts = String(cron).trim().split(/\s+/); if (parts.length !== 5) return false; return cronPart(parts[0], date.getUTCMinutes(), 0, 59) && cronPart(parts[1], date.getUTCHours(), 0, 23) && cronPart(parts[2], date.getUTCDate(), 1, 31) && cronPart(parts[3], date.getUTCMonth() + 1, 1, 12) && cronPart(parts[4], date.getUTCDay(), 0, 6); }
export async function ensureJobDefinitions() { for (const type of backgroundJobs.listTypes()) { const [name, description] = names[type] || [type, `Execute ${type}.`]; await query(`INSERT INTO job_definitions(type,name,description) VALUES($1,$2,$3) ON CONFLICT(type) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,updated_at=NOW()`, [type, name, description]); } }
export async function listJobDefinitions() { await ensureJobDefinitions(); const { rows } = await query('SELECT type,name,description,enabled,default_priority AS "defaultPriority",default_timeout_ms AS "defaultTimeoutMs",supports_pause AS "supportsPause" FROM job_definitions ORDER BY name'); return rows.map((row) => ({ ...row, registered: backgroundJobs.listTypes().includes(row.type) })); }
export async function listJobSchedules() { const { rows } = await query('SELECT id,job_type AS "jobType",name,cron,timezone,enabled,payload,last_run_at AS "lastRunAt",next_run_at AS "nextRunAt",last_error AS "lastError" FROM job_schedules ORDER BY next_run_at NULLS LAST,name'); return rows; }
export async function saveJobSchedule(input, userId) { if (!input?.jobType || !/^([*0-9,/-]+\s+){4}[*0-9,/-]+$/.test(String(input.cron || '').trim())) throw Object.assign(new Error('Cron inválido. Use cinco campos.'), { statusCode: 400 }); const type = String(input.jobType); if (!backgroundJobs.listTypes().includes(type)) throw Object.assign(new Error('Tipo de job não registrado.'), { statusCode: 400 }); const id = input.id || randomUUID(); await query(`INSERT INTO job_schedules(id,job_type,name,cron,timezone,enabled,payload,created_by,next_run_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,NOW()) ON CONFLICT(id) DO UPDATE SET job_type=EXCLUDED.job_type,name=EXCLUDED.name,cron=EXCLUDED.cron,timezone=EXCLUDED.timezone,enabled=EXCLUDED.enabled,payload=EXCLUDED.payload,updated_at=NOW()`, [id,type,String(input.name || type),String(input.cron).trim(),String(input.timezone || 'UTC'),input.enabled !== false,JSON.stringify(input.payload || {}),userId]); return (await listJobSchedules()).find((schedule) => schedule.id === id); }
export async function deleteJobSchedule(id) { const result = await query('DELETE FROM job_schedules WHERE id=$1', [id]); return { deleted: Boolean(result.rowCount) }; }
export function runJob(type, payload = {}, options = {}) { if (!backgroundJobs.listTypes().includes(type)) throw Object.assign(new Error('Tipo de job não registrado.'), { statusCode: 400 }); return backgroundJobs.enqueue(type, payload, options); }
export async function jobExecution(id) { const job = await query('SELECT id,type,status,payload,attempts,max_attempts AS "maxAttempts",timeout_ms AS "timeoutMs",worker_id AS "workerId",error,created_at AS "createdAt",started_at AS "startedAt",completed_at AS "completedAt",updated_at AS "updatedAt",cancel_requested AS "cancelRequested" FROM background_jobs WHERE id=$1', [id]); if (!job.rows[0]) return null; const logs = await query('SELECT id,level,message,details,created_at AS "createdAt" FROM job_logs WHERE job_id=$1 ORDER BY created_at ASC', [id]); return { ...job.rows[0], logs: logs.rows }; }
export async function jobCenterOverview({ recentPage = 1, recentPageSize = 5 } = {}) { const page = Math.max(1, Number(recentPage) || 1); const pageSize = Math.min(12, Math.max(1, Number(recentPageSize) || 5)); const summary = await query("SELECT status,COUNT(*)::int AS total FROM background_jobs GROUP BY status"); const count = await query('SELECT COUNT(*)::int AS total FROM background_jobs'); const recent = await query('SELECT id,type,status,error,created_at AS "createdAt",completed_at AS "completedAt" FROM background_jobs ORDER BY updated_at DESC LIMIT $1 OFFSET $2', [pageSize, (page - 1) * pageSize]); const upcoming = await query('SELECT id,job_type AS "jobType",name,cron,next_run_at AS "nextRunAt" FROM job_schedules WHERE enabled=TRUE ORDER BY next_run_at NULLS LAST LIMIT 8'); return { metrics: Object.fromEntries(summary.rows.map((row) => [row.status, row.total])), recent: recent.rows, recentPagination: { page, pageSize, total: count.rows[0].total, pages: Math.max(1, Math.ceil(Number(count.rows[0].total) / pageSize)) }, upcoming: upcoming.rows }; }
export function cronMatchesForTest(cron, date) { return cronMatches(cron, date); }
