import { randomUUID } from 'node:crypto';
import { query } from '../database/postgres.js';
import { logger } from './logger.js';

const priorities={low:1,normal:2,high:3};
function deferred(){let resolve,reject;const promise=new Promise((ok,fail)=>{resolve=ok;reject=fail;});return{promise,resolve,reject};}
export class JobQueue{
  constructor({concurrency=1,defaultTimeoutMs=120000}={}){this.concurrency=Math.max(1,concurrency);this.defaultTimeoutMs=defaultTimeoutMs;this.handlers=new Map();this.pending=[];this.running=new Map();this.deduplicated=new Map();}
  register(type,handler){
    this.handlers.set(type,handler);
    void this.recover(type)
      .catch((error)=>{
        // Em uma instalação nova, módulos podem registrar handlers antes que a
        // migration assíncrona crie a fila. Não derrube o processo: ainda não há
        // jobs persistidos a recuperar nesse cenário.
        if(error?.code!=='42P01')logger.error('job.recovery_failed',{type,error});
      })
      .finally(()=>this.process());
  }
  rowToJob(row){const pending=deferred();pending.promise.catch(()=>{});return{id:row.id,type:row.type,payload:row.payload||{},priority:Number(row.priority||2),priorityName:Object.entries(priorities).find(([,v])=>v===Number(row.priority))?.[0]||'normal',maxAttempts:Math.max(1,Number(row.max_attempts||3)),timeoutMs:Number(row.timeout_ms||this.defaultTimeoutMs),attempts:Number(row.attempts||0),createdAt:new Date(row.created_at).toISOString(),dedupeKey:row.dedupe_key,...pending};}
  addRecovered(row){if(this.deduplicated.has(row.dedupe_key))return this.deduplicated.get(row.dedupe_key);const job=this.rowToJob(row);this.deduplicated.set(job.dedupeKey,job);this.pending.push(job);return job;}
  async recover(type){await query("UPDATE background_jobs SET status='queued',started_at=NULL,updated_at=NOW(),error=COALESCE(error,'Processo interrompido; trabalho recuperado no reinício.') WHERE type=$1 AND status='running'",[type]);const {rows}=await query("SELECT * FROM background_jobs WHERE type=$1 AND status='queued' ORDER BY priority DESC,created_at ASC",[type]);rows.forEach((row)=>{if(!this.running.has(row.id)&&!this.pending.some((job)=>job.id===row.id))this.addRecovered(row);});}
  enqueue(type,payload,{priority='normal',maxAttempts=3,timeoutMs,dedupeKey}={}){const key=dedupeKey||`${type}:${JSON.stringify(payload)}`;const existing=this.deduplicated.get(key);if(existing)return existing.promise;const pending=deferred();const job={id:randomUUID(),type,payload,priority:priorities[priority]||2,priorityName:priorities[priority]?priority:'normal',maxAttempts:Math.max(1,maxAttempts),timeoutMs:timeoutMs||this.defaultTimeoutMs,attempts:0,createdAt:new Date().toISOString(),dedupeKey:key,...pending};this.deduplicated.set(key,job);void this.persistAndQueue(job);return job.promise;}
  async persistAndQueue(job){try{await query("INSERT INTO background_jobs(id,type,dedupe_key,priority,payload,status,attempts,max_attempts,timeout_ms,created_at,updated_at) VALUES($1,$2,$3,$4,$5::jsonb,'queued',0,$6,$7,$8,NOW())",[job.id,job.type,job.dedupeKey,job.priority,JSON.stringify(job.payload||{}),job.maxAttempts,job.timeoutMs,job.createdAt]);this.pending.push(job);this.process();}catch(error){if(error.code==='23505'){const {rows}=await query("SELECT * FROM background_jobs WHERE dedupe_key=$1 AND status IN ('queued','running') LIMIT 1",[job.dedupeKey]);this.deduplicated.delete(job.dedupeKey);if(rows[0]){const recovered=this.addRecovered(rows[0]);recovered.promise.then(job.resolve,job.reject);this.process();return;}}this.deduplicated.delete(job.dedupeKey);job.reject(error);}}
  async persistRunning(job){await query("UPDATE background_jobs SET status='running',attempts=$1,started_at=NOW(),error=NULL,updated_at=NOW() WHERE id=$2",[job.attempts,job.id]);}
  async persistRetry(job,error){await query("UPDATE background_jobs SET status='queued',error=$1,started_at=NULL,updated_at=NOW() WHERE id=$2",[String(error?.message||error).slice(0,2000),job.id]);}
  async persistFinished(job,status,error=null){await query('UPDATE background_jobs SET status=$1,error=$2,completed_at=NOW(),updated_at=NOW() WHERE id=$3',[status,error?String(error?.message||error).slice(0,2000):null,job.id]);}
  async execute(job){const handler=this.handlers.get(job.type);if(!handler)throw new Error(`Nenhum handler registrado para o job ${job.type}.`);job.attempts+=1;await this.persistRunning(job);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`Job ${job.type} excedeu o tempo limite.`)),job.timeoutMs);Promise.resolve(handler(job.payload,job)).then((value)=>{clearTimeout(timer);resolve(value);},(error)=>{clearTimeout(timer);reject(error);});});}
  process(){while(this.running.size<this.concurrency&&this.pending.length){this.pending.sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt));const job=this.pending.shift();this.running.set(job.id,job);let retrying=false;this.execute(job).then(async(value)=>{await this.persistFinished(job,'completed');logger.info('job.completed',{jobId:job.id,type:job.type,attempts:job.attempts});job.resolve(value);}).catch(async(error)=>{if(job.attempts<job.maxAttempts){retrying=true;await this.persistRetry(job,error);this.pending.push(job);logger.warn('job.retrying',{jobId:job.id,type:job.type,attempt:job.attempts,error});return;}await this.persistFinished(job,'failed',error);logger.error('job.failed',{jobId:job.id,type:job.type,attempts:job.attempts,error});job.reject(error);}).finally(()=>{this.running.delete(job.id);if(!retrying)this.deduplicated.delete(job.dedupeKey);this.process();});}}
  status(type){const matches=(job)=>!type||job.type===type;return{pending:this.pending.filter(matches).length,processing:[...this.running.values()].filter(matches).length,concurrency:this.concurrency};}
  async history({type=null,limit=50}={}){const {rows}=await query('SELECT id,type,dedupe_key AS "dedupeKey",priority,status,attempts,max_attempts AS "maxAttempts",error,created_at AS "createdAt",started_at AS "startedAt",completed_at AS "completedAt" FROM background_jobs WHERE ($1::text IS NULL OR type=$1) ORDER BY created_at DESC LIMIT $2',[type,Math.max(1,Math.min(Number(limit)||50,500))]);return rows;}
  async cancel(id){const index=this.pending.findIndex((job)=>job.id===id);if(index<0)return{cancelled:false,reason:this.running.has(id)?'running-not-cancellable':'not-found'};const[job]=this.pending.splice(index,1);this.deduplicated.delete(job.dedupeKey);await this.persistFinished(job,'cancelled',new Error('Cancelado pelo usuário.'));job.reject(new Error('Job cancelado.'));return{cancelled:true,id};}
  async retry(id){const {rows}=await query("UPDATE background_jobs SET status='queued',attempts=0,error=NULL,started_at=NULL,completed_at=NULL,updated_at=NOW() WHERE id=$1 AND status IN ('failed','cancelled') RETURNING *",[id]);if(!rows[0])return{queued:false,reason:'not-retryable'};this.addRecovered(rows[0]);this.process();return{queued:true,id};}
}
