import { randomUUID } from 'node:crypto';
import { query, withTransaction } from '../database/postgres.js';

const normalize = (value = '') => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
const DEFAULT_PREFERENCES = { preferredFormats: { reflowable: ['epub', 'mobi', 'pdf'], comic: ['cbz', 'cbr'] }, readingMode: 'page', pageAnimation: false, theme: 'system', typography: { scale: 1, lineHeight: 1.8 }, webtoonPreference: 'auto', zoom: 1, fit: 'page' };

export async function listSavedViews(profileId) { const { rows } = await query('SELECT id,name,query_json AS "query",created_at AS "createdAt",updated_at AS "updatedAt" FROM saved_views WHERE profile_id=$1 ORDER BY LOWER(name)', [profileId]); return rows; }
export async function saveView(profileId, input) { const name=String(input?.name||'').trim().slice(0,80); if(!name)throw Object.assign(new Error('Informe um nome para a visualização.'),{statusCode:400}); const id=input.id||randomUUID(); await query('INSERT INTO saved_views(id,profile_id,name,query_json) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,query_json=EXCLUDED.query_json,updated_at=NOW()',[id,profileId,name,JSON.stringify(input.query||{})]); return (await listSavedViews(profileId)).find((item)=>item.id===id); }
export async function deleteView(profileId,id){const result=await query('DELETE FROM saved_views WHERE id=$1 AND profile_id=$2',[id,profileId]);return result.rowCount>0;}

export async function getPreferences(profileId,workId){const {rows:profiles}=await query('SELECT preferences FROM profiles WHERE id=$1',[profileId]);let override={};if(workId){const {rows}=await query('SELECT preferences FROM book_preferences WHERE profile_id=$1 AND work_id=$2',[profileId,workId]);override=rows[0]?.preferences||{};}return{...DEFAULT_PREFERENCES,...(profiles[0]?.preferences||{}),...override};}
export async function savePreferences(profileId,preferences,workId=null){if(workId)await query('INSERT INTO book_preferences(profile_id,work_id,preferences) VALUES($1,$2,$3::jsonb) ON CONFLICT(profile_id,work_id) DO UPDATE SET preferences=EXCLUDED.preferences,updated_at=NOW()',[profileId,workId,JSON.stringify(preferences||{})]);else await query('UPDATE profiles SET preferences=$1::jsonb,updated_at=NOW() WHERE id=$2',[JSON.stringify(preferences||{}),profileId]);return getPreferences(profileId,workId);}

export function naturalVolume(value){const n=Number.parseFloat(String(value).replace(',','.'));return Number.isFinite(n)?n:Number.MAX_SAFE_INTEGER;}
export function detectSeries(title=''){const match=String(title).match(/^(.+?)(?:\s*[-–—:]?\s*)(?:vol(?:ume)?\.?|livro|book|tomo|#)\s*(\d+(?:[.,]\d+)?)/i);return match?{name:match[1].trim(),volume:naturalVolume(match[2]),confidence:.72,source:'filename-pattern'}:null;}
export async function syncSeries(){const {rows:works}=await query('SELECT id,canonical_title AS title,series_name,series_volume,series_confidence,series_source FROM works');let linked=0;for(const work of works){const detected=work.series_name?{name:work.series_name,volume:work.series_volume,confidence:work.series_confidence||1,source:work.series_source||'metadata'}:detectSeries(work.title);if(!detected||detected.confidence<.7)continue;const normalized=normalize(detected.name);if(!normalized)continue;const id=`series-${Buffer.from(normalized).toString('base64url')}`;await withTransaction(async(client)=>{await client.query('INSERT INTO series(id,name,normalized_name) VALUES($1,$2,$3) ON CONFLICT(normalized_name) DO UPDATE SET name=EXCLUDED.name,updated_at=NOW()',[id,detected.name,normalized]);await client.query('INSERT INTO work_series(work_id,series_id,volume,sequence,confidence,source) VALUES($1,$2,$3,$3,$4,$5) ON CONFLICT(work_id) DO UPDATE SET series_id=EXCLUDED.series_id,volume=EXCLUDED.volume,sequence=EXCLUDED.sequence,confidence=EXCLUDED.confidence,source=EXCLUDED.source',[work.id,id,detected.volume,detected.confidence,detected.source]);});linked+=1;}return{linked};}
export async function listSeries(){const {rows}=await query('SELECT s.id,s.name,ws.work_id AS "workId",ws.volume,ws.sequence,w.canonical_title AS title,w.cover_file_id AS "fileId" FROM series s LEFT JOIN work_series ws ON ws.series_id=s.id LEFT JOIN works w ON w.id=ws.work_id ORDER BY LOWER(s.name),COALESCE(ws.sequence,ws.volume,999999),LOWER(w.canonical_title)');const grouped=new Map();for(const row of rows){if(!grouped.has(row.id))grouped.set(row.id,{id:row.id,name:row.name,volumes:0,items:[]});if(row.workId){grouped.get(row.id).items.push({workId:row.workId,fileId:row.fileId,title:row.title,volume:row.volume,sequence:row.sequence});grouped.get(row.id).volumes+=1;}}return[...grouped.values()];}
export async function getSeries(id){const {rows}=await query('SELECT * FROM series WHERE id=$1',[id]);if(!rows[0])return null;const {rows:volumes}=await query('SELECT w.*,ws.volume,ws.sequence,ws.confidence,ws.source FROM work_series ws JOIN works w ON w.id=ws.work_id WHERE ws.series_id=$1 ORDER BY COALESCE(ws.sequence,ws.volume,999999),LOWER(w.canonical_title)',[id]);return{...rows[0],volumes};}
export async function listFlags(){const {rows}=await query('SELECT name,enabled,config FROM feature_flags');return Object.fromEntries(rows.map((row)=>[row.name,{enabled:Boolean(row.enabled),config:row.config||{}}]));}
export async function recordReaderMetric({profileId,workId,fileId,engine,event,durationMs,detail}){await query('INSERT INTO reader_metrics(profile_id,work_id,file_id,engine,event,duration_ms,detail) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[profileId||null,workId||null,fileId||null,engine||'unknown',event||'unknown',Number(durationMs||0),JSON.stringify(detail||{})]);}
export async function readerMetricSummary(){const {rows}=await query("SELECT engine,event,COUNT(*)::int AS total,ROUND(AVG(duration_ms)::numeric,2)::float AS \"avgMs\" FROM reader_metrics WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY engine,event ORDER BY total DESC");return rows;}
export async function duplicateCandidates(){const {rows:decisions}=await query("SELECT work_a_id||':'||work_b_id AS pair FROM duplicate_decisions WHERE decision='ignore'");const ignored=new Set(decisions.map((row)=>row.pair));const {rows:works}=await query('SELECT id,canonical_title AS title,authors,isbn10,isbn13 FROM works ORDER BY canonical_title');const groups=new Map();for(const work of works){const key=normalize(work.title);if(key.length<4)continue;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(work);}const result=[];for(const values of groups.values())for(let i=0;i<values.length;i++)for(let j=i+1;j<values.length;j++){const a=values[i],b=values[j];if(!ignored.has(`${a.id}:${b.id}`)&&!ignored.has(`${b.id}:${a.id}`))result.push({id:`${a.id}:${b.id}`,a,b,reasons:['Título normalizado idêntico']});}return result.slice(0,100);}
export async function decideDuplicate({workAId,workBId,action,apply=false}){if(!['associate','ignore'].includes(action))throw Object.assign(new Error('Ação de duplicata inválida.'),{statusCode:400});const {rows}=await query('SELECT id FROM works WHERE id=ANY($1::text[])',[workAId,workBId]);if(rows.length!==2)throw Object.assign(new Error('Obra não encontrada.'),{statusCode:404});const count=await query('SELECT COUNT(*)::int AS total FROM work_files WHERE work_id=$1',[workBId]);const preview={action,workAId,workBId,filesAffected:count.rows[0].total};if(!apply)return{...preview,dryRun:true};await withTransaction(async(client)=>{if(action==='ignore')await client.query('INSERT INTO duplicate_decisions(id,work_a_id,work_b_id,decision) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET decision=EXCLUDED.decision',[randomUUID(),workAId,workBId,'ignore']);else{await client.query('UPDATE work_files SET work_id=$1 WHERE work_id=$2',[workAId,workBId]);await client.query('DELETE FROM works WHERE id=$1',[workBId]);}});return{...preview,dryRun:false};}

const EXPORT_FIELDS=['id','nome','autor','editora','ano','isbn','isbn10','isbn13','descricao','idioma','tags','categoria'];
export async function exportMetadata(format='json'){const {rows}=await query(`SELECT ${EXPORT_FIELDS.join(',')} FROM livros ORDER BY nome`);if(format==='csv'){const cell=(value)=>`"${String(typeof value==='object'?JSON.stringify(value):(value??'')).replace(/"/g,'""')}"`;return{mime:'text/csv; charset=utf-8',extension:'csv',body:[EXPORT_FIELDS.join(','),...rows.map((row)=>EXPORT_FIELDS.map((field)=>cell(row[field])).join(','))].join('\n')};}return{mime:'application/json',extension:'json',body:JSON.stringify({schema:'araru-metadata',version:2,exportedAt:new Date().toISOString(),data:rows},null,2)};}
export async function importMetadata(payload,{apply=false}={}){if(!['biblioteca-digital-metadata','araru-metadata'].includes(payload?.schema)||![1,2].includes(payload.version)||!Array.isArray(payload.data))throw Object.assign(new Error('Schema de importação inválido.'),{statusCode:400});const changes=[],conflicts=[];for(const row of payload.data){if(!row?.id)continue;const {rows}=await query('SELECT * FROM livros WHERE id=$1',[row.id]);const current=rows[0];if(!current){conflicts.push({id:row.id,type:'missing-file',message:'O arquivo não existe neste catálogo.'});continue;}const patch=Object.fromEntries(EXPORT_FIELDS.filter((field)=>field!=='id'&&row[field]!==undefined&&JSON.stringify(row[field])!==JSON.stringify(current[field])).map((field)=>[field,row[field]]));if(Object.keys(patch).length)changes.push({id:row.id,patch});}if(apply)await withTransaction(async(client)=>{for(const change of changes){const entries=Object.entries(change.patch);const assignments=entries.map(([key],index)=>`"${key}"=$${index+1}${['autor','tags'].includes(key)?'::jsonb':''}`).join(',');const values=entries.map(([key,value])=>['autor','tags'].includes(key)?JSON.stringify(value):value);await client.query(`UPDATE livros SET ${assignments},updated_at=NOW() WHERE id=$${entries.length+1}`,[...values,change.id]);}});return{dryRun:!apply,changes:changes.length,conflicts,items:changes.slice(0,100)};}
