import { randomUUID } from 'node:crypto';
import { query, withTransaction } from '../database/postgres.js';

export async function profileExists(id) { const { rows } = await query('SELECT id FROM profiles WHERE id = $1', [id]); return Boolean(rows[0]); }
export async function resolveProfile(id) { return await profileExists(id) ? id : 'default'; }
export async function listarPerfis(userId = null, all = false) { const params = userId && !all ? [userId] : []; const join = userId && !all ? 'JOIN user_profiles selected ON selected.profile_id=p.id AND selected.user_id=$1' : ''; const { rows } = await query(`SELECT p.id,p.name,p.color,p.avatar_url AS "avatarUrl",p.language,p.theme,p.active,${userId && !all ? 'selected.is_default' : 'p.is_default'} AS "isDefault",p.created_at AS "createdAt",COALESCE(jsonb_agg(jsonb_build_object('id',u.id,'username',u.username,'displayName',u.display_name)) FILTER (WHERE u.id IS NOT NULL),'[]'::jsonb) AS users FROM profiles p ${join} LEFT JOIN user_profiles memberships ON memberships.profile_id=p.id LEFT JOIN users u ON u.id=memberships.user_id ${all ? '' : 'WHERE p.active=TRUE'} GROUP BY p.id${userId && !all ? ',selected.is_default' : ''} ORDER BY "isDefault" DESC,p.name`, params); return rows; }
export async function criarPerfil({ name, color = '#0891B2', language = 'pt-BR', theme = 'system', avatarUrl = null, userIds = [] } = {}) { const cleanName = String(name || '').trim().slice(0, 60); if (!cleanName) throw Object.assign(new Error('Nome do perfil é obrigatório.'), { statusCode: 400 }); const id = randomUUID(); await withTransaction(async(client)=>{await client.query('INSERT INTO profiles(id,name,color,is_default,language,theme,avatar_url) VALUES($1,$2,$3,FALSE,$4,$5,$6)',[id,cleanName,/^#[0-9a-f]{6}$/i.test(color)?color:'#0891B2',language==='en'?'en':'pt-BR',['system','dark','light'].includes(theme)?theme:'system',avatarUrl]);for(const userId of [...new Set(userIds)])await client.query('INSERT INTO user_profiles(user_id,profile_id,is_default) VALUES($1,$2,FALSE) ON CONFLICT DO NOTHING',[userId,id]);}); return (await listarPerfis(null,true)).find(profile=>profile.id===id); }
export async function atualizarPerfil(id, patch = {}) { const { rows } = await query('SELECT * FROM profiles WHERE id = $1', [id]); const current = rows[0]; if (!current) return null; const name = String(patch.name ?? current.name).trim().slice(0, 60); const color = /^#[0-9a-f]{6}$/i.test(patch.color) ? patch.color : current.color; const language=['pt-BR','en'].includes(patch.language)?patch.language:current.language;const theme=['system','dark','light'].includes(patch.theme)?patch.theme:current.theme;await query('UPDATE profiles SET name=$1,color=$2,language=$3,theme=$4,avatar_url=$5,preferences=$6::jsonb,updated_at=NOW() WHERE id=$7',[name,color,language,theme,patch.avatarUrl??current.avatar_url,JSON.stringify(patch.preferences??current.preferences??{}),id]); return (await listarPerfis(null,true)).find((profile) => profile.id === id); }
export async function removerPerfil(id) { if (id === 'default') throw Object.assign(new Error('O perfil principal não pode ser removido.'), { statusCode: 400 }); return withTransaction(async (client) => { await client.query('DELETE FROM reading_state WHERE profile_id = $1', [id]); const result = await client.query('DELETE FROM profiles WHERE id = $1', [id]); return result.rowCount > 0; }); }
export async function usuarioPossuiPerfil(userId, profileId) { const { rows } = await query('SELECT 1 FROM user_profiles WHERE user_id=$1 AND profile_id=$2', [userId, profileId]); return Boolean(rows[0]); }
export async function selecionarPerfilSessao(sessionId, userId, profileId) { if (!await usuarioPossuiPerfil(userId, profileId)) return false; await query('UPDATE user_sessions SET active_profile_id=$1,last_seen_at=NOW() WHERE id=$2 AND user_id=$3', [profileId, sessionId, userId]); return true; }
export async function definirUsuariosPerfil(profileId, userIds = []) { return withTransaction(async(client)=>{const exists=await client.query('SELECT 1 FROM profiles WHERE id=$1',[profileId]);if(!exists.rowCount)return false;await client.query('DELETE FROM user_profiles WHERE profile_id=$1',[profileId]);for(const userId of [...new Set(userIds)])await client.query('INSERT INTO user_profiles(user_id,profile_id,is_default) VALUES($1,$2,FALSE)',[userId,profileId]);await client.query(`UPDATE user_profiles up SET is_default=TRUE WHERE profile_id=$1 AND NOT EXISTS(SELECT 1 FROM user_profiles current WHERE current.user_id=up.user_id AND current.is_default=TRUE)`,[profileId]);return true;}); }
