import { randomUUID } from 'node:crypto';
import { query, withTransaction } from '../database/postgres.js';
import { permissionList } from './permissionRegistry.js';
import { recordAdminAudit } from './adminService.js';

const dto = (row) => row && ({ id: row.id, name: row.name, description: row.description, isSystem: row.is_system, enabled: row.enabled, version: Number(row.version), permissions: row.permissions || [], libraryAccess: row.library_access || [], userCount: Number(row.user_count || 0) });
export async function listRoles() { const { rows } = await query(`SELECT r.*,COALESCE((SELECT jsonb_agg(rp.permission ORDER BY rp.permission) FROM role_permissions rp WHERE rp.role_id=r.id),'[]') permissions,COALESCE((SELECT jsonb_agg(jsonb_build_object('libraryId',rla.library_id,'accessLevel',rla.access_level)) FROM role_library_access rla WHERE rla.role_id=r.id),'[]') library_access,(SELECT COUNT(*) FROM users u WHERE u.role_id=r.id) user_count FROM roles r ORDER BY r.is_system DESC,r.name`); return rows.map(dto); }
export async function getRole(id) { return (await listRoles()).find((role) => role.id === id) || null; }
function validate(input) { const name = String(input.name || '').trim().slice(0, 80); if (!name) throw Object.assign(new Error('Nome da role é obrigatório.'), { statusCode: 400 }); const selected = [...new Set(input.permissions || [])]; if (selected.some((permission) => !permissionList.includes(permission))) throw Object.assign(new Error('Permissão inválida.'), { statusCode: 400 }); return { name, description: String(input.description || '').slice(0, 300), permissions: selected, libraryAccess: input.libraryAccess || [] }; }
export async function saveRole(input, actorId) { const value = validate(input); const id = input.id || randomUUID(); await withTransaction(async (client) => { const current = input.id ? (await client.query('SELECT * FROM roles WHERE id=$1 FOR UPDATE', [id])).rows[0] : null; if (current?.is_system && input.name && input.name !== current.name) throw Object.assign(new Error('Roles internas não podem ser renomeadas.'), { statusCode: 409 }); await client.query(`INSERT INTO roles(id,name,description,is_system) VALUES($1,$2,$3,FALSE) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,updated_at=NOW(),version=roles.version+1`, [id, value.name, value.description]); if (current?.is_system) return; await client.query('DELETE FROM role_permissions WHERE role_id=$1', [id]); for (const permission of value.permissions) await client.query('INSERT INTO role_permissions(role_id,permission) VALUES($1,$2)', [id, permission]); await client.query('DELETE FROM role_library_access WHERE role_id=$1', [id]); for (const access of value.libraryAccess) if (['none','read','manage'].includes(access.accessLevel)) await client.query('INSERT INTO role_library_access(role_id,library_id,access_level) VALUES($1,$2,$3)', [id, access.libraryId, access.accessLevel]); await recordAdminAudit(actorId, input.id ? 'role.updated' : 'role.created', 'role', id, { name: value.name }, client); }); return getRole(id); }
export async function deleteRole(id, replacementRoleId, actorId) { return withTransaction(async (client) => { const role = (await client.query('SELECT * FROM roles WHERE id=$1 FOR UPDATE', [id])).rows[0]; if (!role) return false; if (role.is_system) throw Object.assign(new Error('Roles internas não podem ser excluídas.'), { statusCode: 409 }); const users = await client.query('SELECT id FROM users WHERE role_id=$1 FOR UPDATE', [id]); if (users.rowCount && !replacementRoleId) throw Object.assign(new Error(`Role usada por ${users.rowCount} usuário(s).`), { statusCode: 409 }); if (users.rowCount) await client.query('UPDATE users SET role_id=$1,updated_at=NOW() WHERE role_id=$2', [replacementRoleId, id]); await client.query('DELETE FROM roles WHERE id=$1', [id]); await recordAdminAudit(actorId, 'role.deleted', 'role', id, { replacementRoleId }, client); return true; }); }
