import { createHash, randomBytes, scryptSync, timingSafeEqual, randomUUID } from 'node:crypto';
import { query } from '../database/postgres.js';

export const hashPassword = (password, salt = randomBytes(16).toString('hex')) => `scrypt:${salt}:${scryptSync(String(password), salt, 64).toString('hex')}`;
export function verifyPassword(password, encoded) { const [, salt, digest] = String(encoded || '').split(':'); if (!salt || !digest) return false; const actual = scryptSync(String(password), salt, 64); const expected = Buffer.from(digest, 'hex'); return actual.length === expected.length && timingSafeEqual(actual, expected); }
export async function userCount() { const { rows } = await query('SELECT COUNT(*)::int AS total FROM users'); return Number(rows[0]?.total || 0); }
function validateUser({ username, password }) { const name = String(username || '').trim().toLowerCase(); if (!/^[a-z0-9._@+-]{3,120}$/.test(name)) throw Object.assign(new Error('Usuário inválido.'), { statusCode: 400 }); if (String(password || '').length < 8) throw Object.assign(new Error('A senha deve ter pelo menos 8 caracteres.'), { statusCode: 400 }); return name; }
export async function createUser({ username, email = null, displayName = null, password, role = 'user', profileId = null, mustChangePassword = false, active = true }) { const name = validateUser({ username, password }); const id = randomUUID(); try { const selected = profileId || (await query('SELECT id FROM profiles WHERE active=TRUE ORDER BY is_default DESC,created_at LIMIT 1')).rows[0]?.id || null; await query('INSERT INTO users (id, username, email, display_name, password_hash, role, profile_id, must_change_password, active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)', [id, name, email || null, displayName || name, hashPassword(password), role === 'admin' ? 'admin' : 'user', selected, mustChangePassword, active]); if (selected) await query('INSERT INTO user_profiles(user_id,profile_id,is_default) VALUES($1,$2,TRUE) ON CONFLICT DO NOTHING', [id, selected]); } catch (error) { if (error.code === '23505') throw Object.assign(new Error('Usuário ou e-mail já existe.'), { statusCode: 409 }); throw error; } return getUserById(id); }
export async function getUserByUsername(username) { const { rows } = await query('SELECT * FROM users WHERE LOWER(username) = LOWER($1) LIMIT 1', [String(username || '').trim()]); return rows[0] || null; }
export async function getUserById(id) { const { rows } = await query('SELECT id, username, email, display_name AS "displayName", avatar_url AS "avatarUrl", role, active, must_change_password AS "mustChangePassword", profile_id AS "profileId", created_at AS "createdAt", last_login_at AS "lastLoginAt" FROM users WHERE id = $1', [id]); return rows[0] || null; }
export async function listUsers() { const { rows } = await query('SELECT id, username, email, display_name AS "displayName", avatar_url AS "avatarUrl", role, active, must_change_password AS "mustChangePassword", profile_id AS "profileId", created_at AS "createdAt", last_login_at AS "lastLoginAt" FROM users ORDER BY username'); return rows; }
async function changePassword(id, password, mustChangePassword) { if (String(password || '').length < 8) throw Object.assign(new Error('A senha deve ter pelo menos 8 caracteres.'), { statusCode: 400 }); await query('UPDATE users SET password_hash = $1, must_change_password = $2, updated_at = NOW() WHERE id = $3', [hashPassword(password), mustChangePassword, id]); }
export async function updatePassword(id, password) { await changePassword(id, password, false); }
export async function resetPassword(id, password) { await changePassword(id, password, true); }
export async function markLogin(id) { await query('UPDATE users SET last_login_at = NOW() WHERE id = $1', [id]); }
export async function authFingerprint() { return createHash('sha256').update(String(await userCount())).digest('hex'); }
