import { createHash, randomBytes, scryptSync, timingSafeEqual, randomUUID } from 'node:crypto';
import { query, withTransaction } from '../database/postgres.js';
import { getSecurityConfig } from './securityConfigService.js';

export const hashPassword = (password, salt = randomBytes(16).toString('hex')) => `scrypt:${salt}:${scryptSync(String(password), salt, 64).toString('hex')}`;
export function verifyPassword(password, encoded) { const [, salt, digest] = String(encoded || '').split(':'); if (!salt || !digest) return false; const actual = scryptSync(String(password), salt, 64); const expected = Buffer.from(digest, 'hex'); return actual.length === expected.length && timingSafeEqual(actual, expected); }
export async function userCount() { const { rows } = await query('SELECT COUNT(*)::int AS total FROM users'); return Number(rows[0]?.total || 0); }
export async function validatePassword(password) { const policy = (await getSecurityConfig()).config.authentication; const value = String(password || ''); if (value.length < policy.minPasswordLength) throw Object.assign(new Error(`A senha deve ter pelo menos ${policy.minPasswordLength} caracteres.`), { statusCode: 400 }); if (policy.strongPassword && policy.requireUppercase && !/[A-ZÀ-Ý]/.test(value)) throw Object.assign(new Error('A senha deve conter pelo menos uma letra maiúscula.'), { statusCode: 400 }); if (policy.strongPassword && policy.requireLowercase && !/[a-zà-ÿ]/.test(value)) throw Object.assign(new Error('A senha deve conter pelo menos uma letra minúscula.'), { statusCode: 400 }); if (policy.strongPassword && policy.requireNumber && !/\d/.test(value)) throw Object.assign(new Error('A senha deve conter pelo menos um número.'), { statusCode: 400 }); if (policy.strongPassword && policy.requireSpecial && !/[^a-zA-Z0-9\s]/.test(value)) throw Object.assign(new Error('A senha deve conter um caractere especial.'), { statusCode: 400 }); return true; }
async function validateUser({ username, password }) { const name = String(username || '').trim().toLowerCase(); if (!/^[a-z0-9._@+-]{3,120}$/.test(name)) throw Object.assign(new Error('Usuário inválido.'), { statusCode: 400 }); await validatePassword(password); return name; }
export async function createUser({ username, email = null, displayName = null, password, roleId = 'role-reader', role = 'user', profileId = null, mustChangePassword = false, active = true }) { const name = await validateUser({ username, password }); const policy = (await getSecurityConfig()).config.authentication; const forcePasswordChange = mustChangePassword || policy.requirePasswordChange; const id = randomUUID(); try { const selected = profileId || (await query('SELECT id FROM profiles WHERE active=TRUE ORDER BY is_default DESC,created_at LIMIT 1')).rows[0]?.id || null; const selectedRole = roleId || (role === 'admin' ? 'role-administrator' : 'role-reader'); await query('INSERT INTO users (id, username, email, display_name, password_hash, password_changed_at, role, role_id, profile_id, must_change_password, active) VALUES ($1,$2,$3,$4,$5,NOW(),$6,$7,$8,$9,$10)', [id, name, email || null, displayName || name, hashPassword(password), role === 'admin' ? 'admin' : 'user', selectedRole, selected, forcePasswordChange, active]); if (selected) await query('INSERT INTO user_profiles(user_id,profile_id,is_default) VALUES($1,$2,TRUE) ON CONFLICT DO NOTHING', [id, selected]); } catch (error) { if (error.code === '23505') throw Object.assign(new Error('Usuário ou e-mail já existe.'), { statusCode: 409 }); throw error; } return getUserById(id); }
export async function getUserByUsername(username) { const { rows } = await query('SELECT * FROM users WHERE LOWER(username) = LOWER($1) LIMIT 1', [String(username || '').trim()]); return rows[0] || null; }
export function passwordStatus(user, policy) { const changedAt = user.password_changed_at || user.passwordChangedAt; if (!policy.passwordExpirationEnabled || !changedAt) return { expired: false, expiresAt: null, warning: false }; const expiresAt = new Date(new Date(changedAt).getTime() + Number(policy.passwordExpirationDays) * 86400000); const remaining = expiresAt.getTime() - Date.now(); return { expired: remaining <= 0, expiresAt: expiresAt.toISOString(), warning: remaining > 0 && remaining <= Number(policy.passwordExpirationWarningDays) * 86400000 }; }
export async function getUserById(id) { const { rows } = await query('SELECT u.id, u.username, u.email, u.display_name AS "displayName", u.avatar_url AS "avatarUrl", u.role, u.role_id AS "roleId", r.name AS "roleName", u.active, u.must_change_password AS "mustChangePassword", u.password_changed_at AS "passwordChangedAt", u.profile_id AS "profileId", u.created_at AS "createdAt", u.last_login_at AS "lastLoginAt" FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id = $1', [id]); return rows[0] || null; }
export async function listUsers() { const { rows } = await query('SELECT u.id, u.username, u.email, u.display_name AS "displayName", u.avatar_url AS "avatarUrl", u.role, u.role_id AS "roleId", r.name AS "roleName", u.active, u.must_change_password AS "mustChangePassword", u.password_changed_at AS "passwordChangedAt", u.profile_id AS "profileId", u.created_at AS "createdAt", u.last_login_at AS "lastLoginAt" FROM users u LEFT JOIN roles r ON r.id=u.role_id ORDER BY u.username'); return rows; }
async function changePassword(id, password, mustChangePassword) { await validatePassword(password); const current = await query('SELECT password_hash FROM users WHERE id=$1', [id]); const currentHash = current.rows[0]?.password_hash; if (!currentHash) throw Object.assign(new Error('Usuário não encontrado.'), { statusCode: 404 }); if (verifyPassword(password, currentHash)) throw Object.assign(new Error('A nova senha deve ser diferente da senha atual.'), { statusCode: 400 }); const policy = (await getSecurityConfig()).config.authentication; if (policy.passwordHistoryEnabled) { const history = await query('SELECT password_hash FROM user_password_history WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2', [id, policy.passwordHistoryCount]); if (history.rows.some((row) => verifyPassword(password, row.password_hash))) throw Object.assign(new Error('A nova senha não pode reutilizar uma senha recente.'), { statusCode: 400 }); } const nextHash = hashPassword(password); await withTransaction(async (client) => { if (policy.passwordHistoryEnabled) { await client.query('INSERT INTO user_password_history(user_id,password_hash) VALUES($1,$2)', [id, currentHash]); await client.query('DELETE FROM user_password_history WHERE user_id=$1 AND id NOT IN (SELECT id FROM user_password_history WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2)', [id, policy.passwordHistoryCount]); } await client.query('UPDATE users SET password_hash=$1, password_changed_at=NOW(), must_change_password=$2, updated_at=NOW() WHERE id=$3', [nextHash, mustChangePassword, id]); }); }
export async function updatePassword(id, password) { await changePassword(id, password, false); }
export async function resetPassword(id, password) { await changePassword(id, password, true); }
export async function markLogin(id) { await query('UPDATE users SET last_login_at = NOW() WHERE id = $1', [id]); }
export async function authFingerprint() { return createHash('sha256').update(String(await userCount())).digest('hex'); }
