import { randomBytes } from 'node:crypto';
import { query } from '../database/postgres.js';
import { getUserById, getUserByUsername, markLogin, passwordStatus, updatePassword, verifyPassword } from '../services/userAuthService.js';
import { completeSetup, getSetupStatus } from '../services/setupService.js';
import { clearAdminBootstrap } from '../services/adminBootstrapService.js';
import { getSecurityConfig } from '../services/securityConfigService.js';
import { getRedisClient } from '../services/redisService.js';
import { effectiveAccess } from '../services/authorizationService.js';

const SESSION_COOKIE = 'araru_session';
export function securityHeaders(req, res, next) { res.set({ 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()', 'Cross-Origin-Resource-Policy': 'cross-origin' }); next(); }
export function createRateLimiter({ windowMs = 60000, max = 300 } = {}) { const clients = new Map(); const safeWindowMs = Math.max(1000, Number(windowMs) || 60000); const safeMax = Math.max(1, Number(max) || 300); return (req, res, next) => { const now = Date.now(); const key = req.ip || req.socket.remoteAddress || 'unknown'; const current = clients.get(key); const entry = !current || current.resetAt <= now ? { count: 0, resetAt: now + safeWindowMs } : current; entry.count += 1; clients.set(key, entry); res.set({ 'RateLimit-Limit': String(safeMax), 'RateLimit-Remaining': String(Math.max(0, safeMax - entry.count)), 'RateLimit-Reset': String(Math.ceil(entry.resetAt / 1000)) }); if (entry.count > safeMax) return res.status(429).set('Retry-After', String(Math.max(1, Math.ceil((entry.resetAt - now) / 1000)))).json({ message: 'Muitas requisições. Tente novamente em instantes.' }); next(); }; }
async function redisCount(key, windowSeconds) { const redis = getRedisClient(); if (!redis) return null; try { const count = await redis.incr(key); if (count === 1) await redis.expire(key, Math.max(1, windowSeconds)); return { count, resetAt: Date.now() + Math.max(1, windowSeconds) * 1000 }; } catch { return null; } }
async function redisLockRemaining(key) { const redis = getRedisClient(); if (!redis) return null; try { const ttl = await redis.ttl(key); return ttl > 0 ? ttl : 0; } catch { return null; } }
export function createDynamicRateLimiter(profile = 'api') { const clients = new Map(); return async (req, res, next) => { try { const config = await getSecurityConfig(); if (!config.config.rateLimit.enabled) return next(); const policy = config.config.rateLimit.profiles[profile] || config.config.rateLimit.profiles.api; const windowSeconds = Math.max(1, Number(policy.windowSeconds)); const max = Math.max(1, Number(policy.max)); const identity = req.ip || req.socket.remoteAddress || 'unknown'; const key = `rate-limit:${profile}:${identity}`; const distributed = await redisCount(key, windowSeconds); const now = Date.now(); const current = clients.get(key); const entry = distributed || (!current || current.resetAt <= now ? { count: 1, resetAt: now + windowSeconds * 1000 } : { ...current, count: current.count + 1 }); if (!distributed) clients.set(key, entry); res.set({ 'RateLimit-Limit': String(max), 'RateLimit-Remaining': String(Math.max(0, max - entry.count)), 'RateLimit-Reset': String(Math.ceil(entry.resetAt / 1000)) }); if (entry.count > max) return res.status(429).set('Retry-After', String(Math.max(1, Math.ceil((entry.resetAt - now) / 1000)))).json({ message: 'Muitas requisições. Tente novamente em instantes.' }); return next(); } catch (error) { return next(error); } }; }
export function createLoginRateLimiter() { const attempts = new Map(); return async (req, res, next) => { try { const security = await getSecurityConfig(); if (!security.config.rateLimit.enabled) return next(); const policy = security.config.authentication; const now = Date.now(); const address = req.ip || req.socket.remoteAddress || 'unknown'; const username = String(req.body?.username || '').trim().toLowerCase() || '(empty)'; const key = `brute-force:${address}:${username}`; const lockKey = `brute-lock:${address}:${username}`; const lockTtl = await redisLockRemaining(lockKey); if (lockTtl) return res.status(429).set('Retry-After', String(lockTtl)).json({ message: 'Muitas tentativas de login. Tente novamente mais tarde.' }); const distributed = await redisCount(key, policy.loginWindowSeconds); const current = attempts.get(key); const entry = distributed || (!current || current.resetAt <= now ? { count: 1, resetAt: now + policy.loginWindowSeconds * 1000, lockedUntil: 0 } : { ...current, count: current.count + 1 }); if (entry.count > policy.maxLoginAttempts) { entry.lockedUntil = now + policy.lockoutSeconds * 1000; const redis = getRedisClient(); if (redis) await redis.set(lockKey, '1', 'EX', Math.max(1, policy.lockoutSeconds)); } if (!distributed) attempts.set(key, entry); const lockedUntil = entry.lockedUntil || 0; res.set({ 'RateLimit-Limit': String(policy.maxLoginAttempts), 'RateLimit-Remaining': String(Math.max(0, policy.maxLoginAttempts - entry.count)), 'RateLimit-Reset': String(Math.ceil(entry.resetAt / 1000)) }); if (lockedUntil > now || entry.count > policy.maxLoginAttempts) return res.status(429).set('Retry-After', String(Math.max(1, Math.ceil((lockedUntil - now) / 1000)))).json({ message: 'Muitas tentativas de login. Tente novamente mais tarde.' }); return next(); } catch (error) { return next(error); } }; }
async function profilesForUser(userId) { const { rows } = await query(`SELECT p.id,p.name,p.color,p.avatar_url AS "avatarUrl",p.language,p.theme,p.preferences,up.is_default AS "isDefault" FROM user_profiles up JOIN profiles p ON p.id=up.profile_id WHERE up.user_id=$1 AND p.active=TRUE ORDER BY up.is_default DESC,p.name`, [userId]); return rows; }
export async function sessionContext(req) { const id = String(req.cookies?.[SESSION_COOKIE] || ''); if (!id) return null; const { rows } = await query(`SELECT s.active_profile_id AS "activeProfileId",u.id AS user_id FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>NOW() AND u.active=TRUE`, [id]); if (!rows[0]) return null; await query('UPDATE user_sessions SET last_seen_at=NOW() WHERE id=$1', [id]); const user = await getUserById(rows[0].user_id); const policy = (await getSecurityConfig()).config.authentication; const status = passwordStatus(user, policy); const enrichedUser = { ...user, passwordExpired: status.expired, passwordExpiresAt: status.expiresAt, passwordExpiryWarning: status.warning }; const profiles = await profilesForUser(user.id); const activeProfile = profiles.find((p) => p.id === rows[0].activeProfileId) || profiles.find((p) => p.isDefault) || profiles[0] || null; return { sessionId: id, user: enrichedUser, profiles, activeProfile }; }
export async function requireAdmin(req, res, next) {
  if (!req.user) return res.status(401).json({ message: 'Autenticação necessária.' });
  if (req.user.role === 'admin') return next();
  const domain = req.path.split('/').filter(Boolean)[1];
  const action = req.method === 'GET' ? 'read' : req.method === 'POST' ? 'create' : req.method === 'DELETE' ? 'delete' : 'update';
  const permission = `${domain}.${action}`;
  try {
    const access = await effectiveAccess(req.user.id);
    if (access.permissions.includes(permission) || access.permissions.includes(`${domain}.manage`) || access.permissions.includes('admin.access')) return next();
    return res.status(403).json({ message: 'Permissão insuficiente.', code: 'FORBIDDEN' });
  } catch (error) { return next(error); }
}
export function requirePermission(permission) { return async (req, res, next) => { if (!req.user) return res.status(401).json({ message: 'Autenticação necessária.' }); try { const access = await effectiveAccess(req.user.id); if (access.permissions.includes(permission) || access.permissions.includes(`${permission.split('.')[0]}.manage`) || access.permissions.includes('admin.access')) return next(); return res.status(403).json({ message: 'Permissão insuficiente.', code: 'FORBIDDEN' }); } catch (error) { return next(error); } }; }
export async function configureAccessV1(app, { sessionSeconds = 86400, secureCookies = false, sameSite = 'lax' } = {}) {
  const cookieOptions = async () => { const current = await getSecurityConfig(); const effectiveSessionSeconds = current.config.sessions.sessionSeconds || sessionSeconds; if (current.config.cookies.sameSite === 'none' && !current.config.cookies.secure) throw Object.assign(new Error('SameSite=None exige Secure=true.'), { statusCode: 500 }); return { httpOnly: true, sameSite: current.config.cookies.sameSite, secure: current.config.cookies.secure, maxAge: effectiveSessionSeconds * 1000, path: '/' }; };
  app.get('/api/v1/system/status', async (_req, res) => res.json(await getSetupStatus()));
  app.post('/api/v1/setup', createRateLimiter({ max: 8, windowMs: 15 * 60 * 1000 }), async (req, res, next) => { try { res.status(201).json(await completeSetup(req.body)); } catch (error) { next(error); } });
  app.post('/api/v1/auth/login', createLoginRateLimiter(), async (req, res) => { const user = await getUserByUsername(req.body?.username); if (!user || !user.active || !verifyPassword(req.body?.password, user.password_hash)) return res.status(401).json({ message: 'Usuário ou senha inválidos.' }); const current = await getSecurityConfig(); const status = passwordStatus(user, current.config.authentication); const effectiveSessionSeconds = current.config.sessions.sessionSeconds || sessionSeconds; const profiles = await profilesForUser(user.id); const activeProfile = profiles.find((p) => p.isDefault) || profiles[0] || null; const id = randomBytes(32).toString('base64url'); await query("INSERT INTO user_sessions(id,user_id,active_profile_id,expires_at) VALUES($1,$2,$3,NOW()+($4 * INTERVAL '1 second'))", [id, user.id, activeProfile?.id || null, effectiveSessionSeconds]); await markLogin(user.id); res.cookie(SESSION_COOKIE, id, await cookieOptions()); res.json({ authenticated: true, mustChangePassword: Boolean(user.must_change_password || status.expired), passwordExpired: status.expired, passwordExpiresAt: status.expiresAt, user: await getUserById(user.id), activeProfile, profiles }); });
  app.get('/api/v1/access/session', async (req, res) => { const context = await sessionContext(req); return context ? res.json({ authenticated: true, ...context }) : res.status(401).json({ authenticated: false }); });
  app.post('/api/v1/auth/logout', async (req, res) => { const id = req.cookies?.[SESSION_COOKIE]; if (id) await query('DELETE FROM user_sessions WHERE id=$1', [id]); res.clearCookie(SESSION_COOKIE, await cookieOptions()); res.status(204).end(); });
  app.post('/api/v1/auth/change-password', async (req, res) => { const context = await sessionContext(req); if (!context) return res.status(401).json({ message: 'Autenticação necessária.' }); try { await updatePassword(context.user.id, req.body?.password); if (context.user.username === 'admin') await clearAdminBootstrap(); res.json({ user: await getUserById(context.user.id) }); } catch (error) { res.status(error.statusCode || 400).json({ message: error.message }); } });
  app.use('/api/v1', async (req, res, next) => { const publicPaths = new Set(['/system/info', '/client-config', '/system/status', '/setup', '/auth/login', '/auth/logout', '/auth/drive/login', '/auth/callback', '/access/session', '/auth/change-password']); if (publicPaths.has(req.path)) return next(); const context = await sessionContext(req); if (context) { if (context.user.mustChangePassword || context.user.passwordExpired) return res.status(428).json({ message: 'Você precisa trocar sua senha antes de continuar.', code: 'PASSWORD_CHANGE_REQUIRED', passwordExpired: context.user.passwordExpired }); req.user = context.user; req.sessionContext = context; req.profileId = context.activeProfile?.id || null; return next(); } const status = await getSetupStatus(); if (status.setupRequired) return res.status(428).json({ message: 'A configuração inicial precisa ser concluída.', code: 'SETUP_REQUIRED' }); return res.status(401).json({ message: 'Autenticação necessária.' }); });
}
