import { StorageError, normalizeRange, providerCapabilities } from './storageProvider.js';

export class GoogleDriveStorageProvider {
  constructor({ client, request = (task) => task() }) { this.client = client; this.request = request; this.type = 'drive'; this.capabilities = providerCapabilities({ list: true, range: true, changeCursor: true, watch: false }); }
  async stat(key, metadata = {}) { if (metadata.size !== undefined || metadata.fileSize !== undefined) return { key, size: Number(metadata.size ?? metadata.fileSize ?? 0), mimeType: metadata.mimeType || 'application/octet-stream', etag: metadata.md5Checksum || metadata.etag || null, modifiedAt: metadata.modifiedTime || null }; try { const result = await this.request(() => this.client.files.get({ fileId: key, fields: 'id,name,size,mimeType,modifiedTime,md5Checksum,trashed' })); if (result.data.trashed) throw new StorageError('Objeto não encontrado.', { code: 'OBJECT_NOT_FOUND', statusCode: 404 }); return { key, size: Number(result.data.size || 0), mimeType: result.data.mimeType, etag: result.data.md5Checksum || null, modifiedAt: result.data.modifiedTime || null }; } catch (error) { if (error instanceof StorageError) throw error; throw this.mapError(error); } }
  async exists(key) { try { await this.stat(key); return true; } catch (error) { if (error.code === 'OBJECT_NOT_FOUND') return false; throw error; } }
  async stream(key, range, metadata = {}, { signal } = {}) { const info = await this.stat(key, metadata); const selected = range ? normalizeRange(range, info.size) : null; try { const result = await this.request(() => this.client.files.get({ fileId: key, alt: 'media' }, { responseType: 'stream', ...(selected ? { headers: { Range: `bytes=${selected.start}-${selected.end}` } } : {}), ...(signal ? { signal } : {}) })); return { ...info, range: selected, stream: result.data }; } catch (error) { throw this.mapError(error); } }
  async list(query, pageSize = 1000) { const files = []; let pageToken; do { const result = await this.request(() => this.client.files.list({ q: query, pageSize: Math.min(1000, pageSize), pageToken, fields: 'nextPageToken,files(id,name,mimeType,parents,webViewLink,thumbnailLink,modifiedTime,size,md5Checksum,trashed)' })); files.push(...(result.data.files || [])); pageToken = result.data.nextPageToken; } while (pageToken); return files; }
  async getFile(key) { try { const result = await this.request(() => this.client.files.get({ fileId: key, fields: 'id,name,mimeType,parents,webViewLink,thumbnailLink,modifiedTime,size,md5Checksum,trashed' })); return result.data; } catch (error) { throw this.mapError(error); } }
  async startPageToken() { try { const result = await this.request(() => this.client.changes.getStartPageToken({})); return result.data.startPageToken || null; } catch (error) { throw this.mapError(error); } }
  async listChanges(pageToken, pageSize = 1000) { const changes = []; let token = pageToken; let nextCursor = pageToken; do { const result = await this.request(() => this.client.changes.list({ pageToken: token, pageSize: Math.min(1000, pageSize), spaces: 'drive', includeRemoved: true, fields: 'nextPageToken,newStartPageToken,changes(fileId,removed,file(id,name,mimeType,parents,trashed,webViewLink,thumbnailLink,modifiedTime,size,md5Checksum))' })); changes.push(...(result.data.changes || [])); token = result.data.nextPageToken; nextCursor = result.data.newStartPageToken || token || nextCursor; } while (token); return { changes, nextCursor }; }
  mapError(error) { const status = Number(error?.code || error?.response?.status || 0); if (status === 404) return new StorageError('Objeto não encontrado.', { code: 'OBJECT_NOT_FOUND', statusCode: 404, cause: error }); if (status === 401 || status === 403) return new StorageError('Acesso negado ao Google Drive.', { code: 'STORAGE_UNAUTHORIZED', statusCode: status, cause: error }); if (status === 429 || status >= 500) return new StorageError('Google Drive temporariamente indisponível.', { code: 'STORAGE_RATE_LIMITED', statusCode: status === 429 ? 429 : 503, cause: error }); return new StorageError('Falha no Google Drive.', { code: 'STORAGE_UNAVAILABLE', statusCode: 503, cause: error }); }
}
