import { Readable } from 'node:stream';
import { AbortMultipartUploadCommand, CompleteMultipartUploadCommand, CreateMultipartUploadCommand, DeleteObjectCommand, GetObjectCommand, HeadBucketCommand, HeadObjectCommand, ListObjectsV2Command, PutObjectCommand, S3Client, UploadPartCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { StorageError, normalizeRange, providerCapabilities } from './storageProvider.js';

const bodyToNodeStream = (body) => body?.getReader ? Readable.fromWeb(body) : body;

export class R2StorageProvider {
  constructor({ endpoint, accessKeyId, secretAccessKey, bucket, region = 'auto', signedUrlTtl = 300, publicUrl = '' }) {
    if (!endpoint || !accessKeyId || !secretAccessKey || !bucket) throw new StorageError('Configuração R2 incompleta.', { code: 'R2_NOT_CONFIGURED', statusCode: 503 });
    this.type = 'r2'; this.bucket = bucket; this.signedUrlTtl = Math.max(30, Number(signedUrlTtl) || 300); this.publicUrl = publicUrl.replace(/\/$/, '');
    this.client = new S3Client({ region, endpoint, forcePathStyle: true, credentials: { accessKeyId, secretAccessKey } });
    this.capabilities = providerCapabilities({ list: true, write: true, delete: true, signedRead: true, signedUpload: true, multipart: true });
  }
  async stat(key) { try { const result = await this.client.send(new HeadObjectCommand({ Bucket: this.bucket, Key: key })); return { key, size: Number(result.ContentLength || 0), mimeType: result.ContentType || 'application/octet-stream', etag: result.ETag, checksum: result.ChecksumSHA256 || result.ChecksumCRC32 || null, modifiedAt: result.LastModified || null, metadata: result.Metadata || {} }; } catch (error) { throw this.mapError(error, 'Não foi possível consultar o objeto R2.'); } }
  async exists(key) { try { await this.stat(key); return true; } catch (error) { if (error.code === 'OBJECT_NOT_FOUND') return false; throw error; } }
  async stream(key, range, _metadata = {}, { signal } = {}) { const info = await this.stat(key); const selected = normalizeRange(range, info.size); try { const result = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key, ...(selected ? { Range: `bytes=${selected.start}-${selected.end}` } : {}) }), signal ? { abortSignal: signal } : undefined); return { ...info, range: selected, stream: bodyToNodeStream(result.Body) }; } catch (error) { throw this.mapError(error, 'Não foi possível ler o objeto R2.'); } }
  async list(prefix = '', maxKeys = 1000) { try { const objects = []; let continuationToken; do { const result = await this.client.send(new ListObjectsV2Command({ Bucket: this.bucket, Prefix: prefix, MaxKeys: Math.min(1000, Math.max(1, maxKeys)), ...(continuationToken ? { ContinuationToken: continuationToken } : {}) })); objects.push(...(result.Contents || []).map((item) => ({ key: item.Key, size: Number(item.Size || 0), etag: item.ETag, modifiedAt: item.LastModified }))); continuationToken = result.IsTruncated ? result.NextContinuationToken : null; } while (continuationToken); return objects; } catch (error) { throw this.mapError(error, 'Não foi possível listar objetos R2.'); } }
  async put(key, body, { contentType, metadata, contentLength } = {}) { try { await this.client.send(new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: body, ...(contentType ? { ContentType: contentType } : {}), ...(metadata ? { Metadata: metadata } : {}), ...(contentLength ? { ContentLength: contentLength } : {}) })); return this.stat(key); } catch (error) { throw this.mapError(error, 'Não foi possível enviar o objeto R2.'); } }
  async delete(key) { try { await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key })); } catch (error) { throw this.mapError(error, 'Não foi possível excluir o objeto R2.'); } }
  async signedReadUrl(key, expiresIn = this.signedUrlTtl) { return getSignedUrl(this.client, new GetObjectCommand({ Bucket: this.bucket, Key: key }), { expiresIn: Math.max(30, Math.min(86400, Number(expiresIn) || this.signedUrlTtl)) }); }
  async signedUploadUrl(key, { contentType, expiresIn = this.signedUrlTtl } = {}) { return getSignedUrl(this.client, new PutObjectCommand({ Bucket: this.bucket, Key: key, ...(contentType ? { ContentType: contentType } : {}) }), { expiresIn: Math.max(30, Math.min(86400, Number(expiresIn) || this.signedUrlTtl)) }); }
  async createMultipart(key, { contentType, metadata } = {}) { try { const result = await this.client.send(new CreateMultipartUploadCommand({ Bucket: this.bucket, Key: key, ...(contentType ? { ContentType: contentType } : {}), ...(metadata ? { Metadata: metadata } : {}) })); return { uploadId: result.UploadId, key }; } catch (error) { throw this.mapError(error, 'Não foi possível iniciar multipart R2.'); } }
  async uploadPart(key, uploadId, partNumber, body, contentLength) { try { const result = await this.client.send(new UploadPartCommand({ Bucket: this.bucket, Key: key, UploadId: uploadId, PartNumber: partNumber, Body: body, ...(contentLength ? { ContentLength: contentLength } : {}) })); return { partNumber, etag: result.ETag }; } catch (error) { throw this.mapError(error, 'Não foi possível enviar parte ao R2.'); } }
  async completeMultipart(key, uploadId, parts) { try { await this.client.send(new CompleteMultipartUploadCommand({ Bucket: this.bucket, Key: key, UploadId: uploadId, MultipartUpload: { Parts: parts.map((part) => ({ PartNumber: part.partNumber, ETag: part.etag })) } })); return this.stat(key); } catch (error) { throw this.mapError(error, 'Não foi possível concluir multipart R2.'); } }
  async abortMultipart(key, uploadId) { try { await this.client.send(new AbortMultipartUploadCommand({ Bucket: this.bucket, Key: key, UploadId: uploadId })); } catch (error) { throw this.mapError(error, 'Não foi possível cancelar multipart R2.'); } }
  async health() { try { await this.client.send(new HeadBucketCommand({ Bucket: this.bucket })); return { configured: true, healthy: true, provider: this.type }; } catch (error) { const mapped = this.mapError(error, 'R2 indisponível.'); return { configured: true, healthy: false, provider: this.type, code: mapped.code, error: mapped.message }; } }
  mapError(error, fallback) { const status = Number(error?.$metadata?.httpStatusCode || 0); if (status === 404 || ['NotFound', 'NoSuchKey', 'NoSuchBucket'].includes(error?.name)) return new StorageError('Objeto não encontrado.', { code: 'OBJECT_NOT_FOUND', statusCode: 404, cause: error }); if (status === 403 || error?.name === 'AccessDenied') return new StorageError('Acesso negado ao storage R2.', { code: 'STORAGE_UNAUTHORIZED', statusCode: 403, cause: error }); if (status === 429) return new StorageError('R2 limitou a requisição.', { code: 'STORAGE_RATE_LIMITED', statusCode: 429, cause: error }); return new StorageError(fallback, { code: 'STORAGE_UNAVAILABLE', statusCode: 503, cause: error }); }
}
